# -*- coding: utf-8 -*-
"""BMI_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJVe26aTqI6UjD8vFTp5HiYmKm2-abNo
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('BMI_data_analysis .csv')
df.head()

df = df.drop('Column 1', axis=1)
df.head()

df = df.rename(columns={
    'Enter your full name': 'Name',
    'Enter your age': 'Age',
    'Enter your Gender': 'Gender',
    'Enter your Height (in cm or ft)': 'Height(in ft or cm)',
    'Enter your Weight(in kg)': 'Weight'
})

print("\nDataFrame after renaming multiple columns:")
df.head()



import re


df['Height(in ft or cm)'] = df['Height(in ft or cm)'].astype(str)

def convert_height_to_meters(height_str):
    height_str = height_str.lower().strip()


    if 'cm' in height_str:
        height_val = re.sub('[^0-9.]', '', height_str)
        if height_val:
            return float(height_val) / 100


    if 'ft' in height_str or 'feet' in height_str:
        feet = 0
        inches = 0

        match_feet = re.search(r'(\d+\.?\d*)\s*(ft|feet)?', height_str)
        if match_feet:
            feet = float(match_feet.group(1))

        match_inches = re.search(r'(\d+)\s*(in|inch|inches)', height_str)
        if match_inches:
            inches = float(match_inches.group(1))

        return (feet * 0.3048) + (inches * 0.0254)


    if re.match(r'^\d+\.?\d*$', height_str):
        return float(height_str) * 0.3048

    return None

df['Height_m'] = df['Height(in ft or cm)'].apply(convert_height_to_meters)

df['Weight'] = (df['Weight']
    .astype(str)
    .str.replace('kgs', '', regex=False)
    .str.replace('kg', '', regex=False)
    .str.strip())
df['Weight'] = pd.to_numeric(df['Weight'], errors='coerce')

df.dropna(subset=['Weight', 'Height_m'], inplace=True)

print("\nConverted Height and Weight:")
print(df[['Name','Height(in ft or cm)','Height_m','Weight']].head())

df.iloc[1]

df['BMI'] = df['Weight'] / (df['Height_m'] ** 2)

def bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi < 25:
        return 'Normal'
    elif 25 <= bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'

df['BMI_Category'] = df['BMI'].apply(bmi_category)

print(df[['Name','Height_m','Weight','BMI','BMI_Category']].head())

category_stats = df.groupby('BMI_Category')['BMI'].agg(['count', 'mean', 'min', 'max', 'std'])
print(category_stats)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print(" DESCRIPTIVE STATISTICS\n")

mean_bmi = df['BMI'].mean()
print("Mean BMI:", round(mean_bmi, 2))

median_bmi = df['BMI'].median()
print("Median BMI:", round(median_bmi, 2))

mode_bmi = df['BMI'].mode()[0]
print("Mode BMI:", round(mode_bmi, 2))

std_bmi = df['BMI'].std()
print("Standard Deviation of BMI:", round(std_bmi, 2))

print("\n BMI CATEGORY DISTRIBUTION\n")

category_counts = df['BMI_Category'].value_counts()
category_percent = df['BMI_Category'].value_counts(normalize=True) * 100

print("BMI Category Counts:\n", category_counts)
print("\nBMI Category Percentage:\n", category_percent.round(2))

plt.figure(figsize=(6,4))
category_percent.plot(kind='bar', color='skyblue', edgecolor='black')
plt.title("BMI Category Distribution", fontsize=14)
plt.xlabel("BMI Category")
plt.ylabel("Percentage (%)")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

print("\n COMPARATIVE ANALYSIS: GENDER vs BMI\n")
plt.figure(figsize=(6,4))
sns.boxplot(x='Gender', y='BMI', data=df, palette='pastel')
plt.title("Gender vs BMI Comparison", fontsize=14)
plt.xlabel("Gender")
plt.ylabel("BMI")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

print("Average BMI by Gender:")
print(df.groupby('Gender')['BMI'].mean().round(2))

print("\n COMPARATIVE ANALYSIS: AGE GROUP vs BMI\n")

bins = [0, 18, 25, 35, 50, 100]
labels = ['<18', '18-25', '26-35', '36-50', '50+']
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

age_bmi = df.groupby('Age_Group')['BMI'].mean()
print(age_bmi.round(2))

plt.figure(figsize=(6,4))
age_bmi.plot(kind='bar', color='lightgreen', edgecolor='black')
plt.title("Average BMI by Age Group", fontsize=14)
plt.xlabel("Age Group")
plt.ylabel("Average BMI")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

print("\n Data Analysis Completed Successfully!")